#!/usr/bin/env bash
# Script that configures /etc/hosts file to change localhost

# Remove old entries and add new ones
grep -v "localhost" /etc/hosts | grep -v "facebook.com" > /tmp/hosts.tmp
echo "127.0.0.2 localhost" >> /tmp/hosts.tmp
echo "8.8.8.8 facebook.com" >> /tmp/hosts.tmp
cp /tmp/hosts.tmp /etc/hosts
rm /tmp/hosts.tmp
